# Generated by Django 6.1.1 on 2026-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='city',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='region',
            field=models.CharField(blank=True, choices=[('REGION_NORTH', 'Norte'), ('REGION_NORTH_EAST', 'Nordeste'), ('REGION_CENTRAL_WEST', 'Centro-Oeste'), ('REGION_SOUTHEAST', 'Sudeste'), ('REGION_SOUTH', 'Sul')], max_length=100, null=True),
        ),
    ]
