# Generated by Django 6.1.1 on 2026-09-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'Youtube'), ('TIK_TOK', 'Tik Tok'), ('X', 'X'), ('WHATSAPP', 'Whatsapp'), ('KAWAI', 'Kawai')], max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
