# Generated by Django 6.1.1 on 2026-09-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosure', '0001_initial'),
        ('enterprise', '0002_remove_enterprise_city_enterprise_region'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='enterprise',
            field=models.ManyToManyField(related_name='enterprises', to='enterprise.enterprise'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.product'),
        ),
    ]
